<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$count_item = count($this->_getProducts());
$helper = Mage::helper('basicproducts/data');
if (!empty($list)) {
	$uniqued = 'sm_basic_products_' . time() . rand();

	$class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);

	?>
	<div class="basic-home col-lg-4 col-md-4 col-sm-6">
		<?php if( $this->_getConfig('basicproducts_title_text') ){ ?>
			<div class="bottom-title">
				<h2 class="bt-title"><?php echo $this->_getConfig('basicproducts_title_text','Basic Products Title'); ?></h2>
			</div>
		<?php } ?>
		
		<?php if ( $this->_getConfig('pretext') != null ) { ?>
			<div class="des-home-block with-bg">
				<p class="des-ct"><?php echo $this->_getConfig('pretext'); ?></p>
			</div>
		<?php } ?>
		
		<div id="<?php echo $uniqued; ?>" class="block-content">
			<!-- Begin bs-items     -->
			<div class="bs-items slider-bs-home <?php echo $class_respl; ?> ">
				<?php  $j = 0;
				$count = 0;
				$nb_rows = 3;
				foreach ($list as $_product) {
					$count ++;
					$j++;
					$show_line = ($this->_getConfig('showline') == 1) ? ' bs-show-line' : '';
					$last_class = ($j == count($list)) ? ' last' : '';
					?>
					<!-- Begin bs-item-cf -->
					<?php if ($count % $nb_rows == 1 || $nb_rows == 1) { ?>
					<div class="item">
					<?php } ?>
					<div class="respl-item-bs">
						<!-- Begin bs-item-inner -->
						<div class="item-inner">
							
							<?php if ( $_product->_image ) { ?>
								<div class="w-image-box">
									<div class="item-image">
										<a href="<?php echo $_product->link ?>"
										   title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
											>
											<img src="<?php echo $_product->_image; ?>"
												 title="<?php echo $_product->title; ?>"
												 alt="<?php echo $_product->title; ?>"
												>
										</a>
									</div>
									
									
								</div>
							<?php } ?>
							
							<!-- Begin bs-content -->
							<div class="item-info">

								<?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
									<div class="item-title">
										<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
											>
											<?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
										</a>
									</div>
								<?php } ?>
								
								
									<?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
										<div class="item-review">
											<div class="bs-review">
												<?php
												$this->addReviewSummaryTemplate('sm', 'sm/basicproducts/default_summary.phtml');
												echo $this->getReviewsSummaryHtml($_product, 'sm', true);
												?>
											</div>
										</div>
									<?php } ?>
								
									<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
										<div class="item-price">
											<?php echo $this->getPriceHtml($_product, true); ?>
										</div>
									<?php } ?>
								
								
									<?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
									
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>"
														class="item-addcart btn-cart"
														onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
													<span><span><?php echo $this->__('Add to Cart') ?></span></span>
										</button>
									
									<?php endif;?>
									
									<div class="btn-bottom">
									
										<?php if ((int)$this->_getConfig('product_addwishlist_display', 1)) :?>
										<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn-button item-wishlist">
											<span><?php echo $this->__('Add to Wishlist') ?></span>
										</a>
										<?php endif;?>
										
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && (int)$this->_getConfig('product_addcompare_display', 1)): ?>
										<a href="<?php echo $_compareUrl ?>" class="btn-button item-compare">
											<span><?php echo $this->__('Add to Compare') ?></span>
										</a>
										<?php endif;?>
									
									</div>
								
								

										<?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->description) != '') { ?>
											<div class="des-content">
												<?php echo $_product->_description; ?>
											</div>
										<?php } ?>
										
										<?php if ($this->_getConfig('cat_title_display') == 1) { ?>
											<div class="bs-category">
												<a href="<?php echo $_product->catlink; ?>"
												   title="<?php echo $_product->category_title; ?>"
													<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
													>
													<?php echo 'Category:&nbsp'.$helper->truncate($_product->category_title, $this->_getConfig('category_title_max_characs', 25)); ?>
												</a>
											</div>
										<?php } ?>

										<?php if ($this->_getConfig('item_date_display') == 1) { ?>
											<div class="bs-date">
												<?php  echo  $_product->created_at; ?>
											</div>
										<?php } ?>

										<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
											<div class="bs-detail">
												<a href="<?php echo $_product->link ?>"
												   title="<?php echo $_product->title; ?>"
													<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
													>
													<?php echo $this->_getConfig('product_readmore_text','Details'); ?>
												</a>
											</div>
										<?php } ?>
								

							</div>
							<!-- End bs-content -->
						</div>
						<!-- End bs-item-inner -->
					</div><!-- End bs-item-cf -->
					<?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
					</div>
					<?php } ?>
				<?php } ?>
			</div>
			<script>
				jQuery(document).ready(function($) {
					var owl_bshome = $(".slider-bs-home");
					owl_bshome.owlCarousel({
						itemsCustom : [
						[0, 1],
						[480, 1],
						[768, 1],
						[992, 1],
						[1200, 1]
						], 

						slideSpeed : 300,
						stopOnHover: true,
						paginationSpeed : 400,
						autoPlay:false,
						pagination: true,
					});	  
				});	
			</script>
			<!-- End bs-items -->
		</div><!-- End Sm-basic-products -->
		<?php if ($this->_getConfig('posttext') != null) { ?>
			<div class="bs-posttext">
				<?php echo $this->_getConfig('posttext'); ?>
			</div>
		<?php } ?>
	</div>


<?php
} else {
	echo 'Has no content to show!';
}?>